version: 0.2

env:
  variables:
    CI: "1"
  parameter-store:
    GITHUB_TOKEN: renovate-aws/GITHUB_TOKEN
    GITLAB_TOKEN: renovate-aws/GITLAB_TOKEN


phases:
  install:
    commands:
      - npm install renovate@${RENOVATE_VERSION}
      - "$(npm bin)/renovate --version"
  build:
    commands:
      - "$(npm bin)/renovate"

cache:
  paths:
    - "node_modules/**/*"
